-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGEdQ+NjnzhSCNqta
y0LYKN/ErJT/egQ98PV9GflB/EOgCgYIKoZIzj0DAQehRANCAATgkWF3kUWH1XM7
1xXRb9mCSNP7R9MMRoi2hqOwEw3mV/q7YIZh5NcMo6NBIStMWmtWQUGdckVBikdP
SjDvS8ge
-----END PRIVATE KEY-----